### ISSUE TITLE
Export current item data

### ISSUE THREAD

**Issue by MrFidgety** [MrFidgety/slick.gifts#10]
Export the entire item table for analysis

**Comment by bstone23** [comment]
ETA?

**Comment by MrFidgety** [comment]
By the end of the week @bstone23

**Comment by bstone23** [comment]
Thanks very much

**Comment by MrFidgety** [comment]
Having trouble exporting the data. More difficult than expected.

**Comment by bstone23** [comment]
Okay. New ETA?

Also, I've created a spreadsheet to monitor our daily growth. You can find it on our Google Drive under the Slick Gifts folder, it's called "Slick Gifts - Growth Chart".

**Comment by MrFidgety** [comment]
Unsure on new eta, need to figure out how to export the info, it has already taken a few hours
